#!/usr/bin/env python3
"""Summarize Octree navigation benchmark CSV files.

Input rows are generated by build/octree_performance_benchmark through
scripts/run_performance_benchmark.sh. The script prints mean metrics by mode,
writes a JSON report, and optionally saves simple bar charts when matplotlib is
available.
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path
from statistics import mean


NUMERIC_FIELDS = [
    "source_points",
    "used_points",
    "parse_ms",
    "build_ms",
    "plan_ms",
    "total_ms",
    "node_count",
    "leaf_count",
    "estimated_node_memory_kb",
    "rss_kb_after",
    "peak_rss_kb",
    "expanded_nodes",
    "waypoints",
    "path_cost",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        default="data/performance_benchmark.csv",
        help="Benchmark CSV generated by run_performance_benchmark.sh",
    )
    parser.add_argument(
        "--output-json",
        default="data/performance_summary.json",
        help="Summary JSON output path",
    )
    parser.add_argument(
        "--plot",
        default="data/performance_summary.png",
        help="Optional matplotlib plot output path",
    )
    parser.add_argument(
        "--table-plot",
        default="data/performance_improvement_table.png",
        help="Optional matplotlib table image output path",
    )
    parser.add_argument(
        "--poster-chart",
        default="data/poster_performance_chart.png",
        help="Poster-ready chart image output path",
    )
    parser.add_argument(
        "--poster-table",
        default="data/poster_performance_table.png",
        help="Poster-ready table image output path",
    )
    parser.add_argument(
        "--output-table",
        default="data/performance_summary.md",
        help="Markdown table output path for report-ready percentage summaries",
    )
    parser.add_argument(
        "--raw-point-bytes",
        type=float,
        default=24.0,
        help=(
            "Estimated raw PointCloudPacked payload bytes per point. "
            "Current x/y/z + label + probability + entity_id cloud is about 24 bytes/point."
        ),
    )
    parser.add_argument(
        "--point-graph-bytes",
        type=float,
        default=96.0,
        help=(
            "Estimated bytes per point when a pure point-cloud A* baseline stores "
            "position, costs, parent/state, and neighbor metadata."
        ),
    )
    return parser.parse_args()


def load_rows(path: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        for row in reader:
            converted: dict[str, object] = dict(row)
            for field in NUMERIC_FIELDS:
                if field in row and row[field] != "":
                    converted[field] = float(row[field])
            converted["path_success"] = row.get("path_success") in {"1", "true", "True"}
            converted["frame"] = int(row.get("frame", 0))
            rows.append(converted)
    return rows


def percentage_reduction(baseline: float, current: float) -> float | None:
    if baseline == 0:
        return None
    return (baseline - current) / baseline * 100.0


def safe_ratio(numerator: float, denominator: float) -> float | None:
    if denominator == 0:
        return None
    return numerator / denominator


def summarize(
    rows: list[dict[str, object]],
    raw_point_bytes: float,
    point_graph_bytes: float,
) -> dict[str, object]:
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in rows:
        grouped[str(row["mode"])].append(row)

    summary: dict[str, object] = {
        "modes": {},
        "assumptions": {
            "raw_point_bytes": raw_point_bytes,
            "point_graph_bytes": point_graph_bytes,
        },
    }
    for mode, items in grouped.items():
        mode_summary: dict[str, object] = {
            "frames": len(items),
            "success_rate": mean(1.0 if item["path_success"] else 0.0 for item in items),
        }
        for field in NUMERIC_FIELDS:
            values = [float(item[field]) for item in items if field in item]
            if values:
                mode_summary[f"mean_{field}"] = mean(values)
                mode_summary[f"min_{field}"] = min(values)
                mode_summary[f"max_{field}"] = max(values)
        used_points = float(mode_summary.get("mean_used_points", 0.0))
        octree_memory_kb = float(mode_summary.get("mean_estimated_node_memory_kb", 0.0))
        raw_cloud_memory_kb = used_points * raw_point_bytes / 1024.0
        point_graph_memory_kb = used_points * point_graph_bytes / 1024.0
        mode_summary["estimated_raw_pointcloud_memory_kb"] = raw_cloud_memory_kb
        mode_summary["estimated_point_graph_memory_kb"] = point_graph_memory_kb
        mode_summary["octree_vs_raw_pointcloud_memory_reduction_percent"] = percentage_reduction(
            raw_cloud_memory_kb,
            octree_memory_kb,
        )
        mode_summary["octree_vs_point_graph_memory_reduction_percent"] = percentage_reduction(
            point_graph_memory_kb,
            octree_memory_kb,
        )
        mean_plan_ms = float(mode_summary.get("mean_plan_ms", 0.0))
        mean_total_ms = float(mode_summary.get("mean_total_ms", 0.0))
        mean_expanded = float(mode_summary.get("mean_expanded_nodes", 0.0))
        mode_summary["planning_hz"] = safe_ratio(1000.0, mean_plan_ms)
        mode_summary["end_to_end_hz"] = safe_ratio(1000.0, mean_total_ms)
        mode_summary["expanded_nodes_per_second"] = (
            safe_ratio(mean_expanded * 1000.0, mean_plan_ms)
        )
        summary["modes"][mode] = mode_summary

    semantic = summary["modes"].get("semantic_octree_astar")
    rf = summary["modes"].get("rf_octree_astar")
    if semantic and rf:
        comparison = {}
        for field in ["total_ms", "build_ms", "plan_ms", "expanded_nodes", "waypoints", "path_cost"]:
            s = semantic.get(f"mean_{field}")
            r = rf.get(f"mean_{field}")
            if s is not None and r is not None:
                comparison[f"rf_minus_semantic_mean_{field}"] = r - s
                improvement = percentage_reduction(float(s), float(r))
                if improvement is not None:
                    comparison[f"rf_vs_semantic_{field}_improvement_percent"] = improvement
                if s != 0:
                    comparison[f"rf_vs_semantic_{field}_ratio"] = r / s
                    comparison[f"semantic_vs_rf_{field}_speedup"] = s / r if r != 0 else None
        for field in ["planning_hz", "end_to_end_hz", "expanded_nodes_per_second"]:
            s = semantic.get(field)
            r = rf.get(field)
            if s is not None and r is not None:
                comparison[f"rf_minus_semantic_{field}"] = r - s
                comparison[f"rf_vs_semantic_{field}_gain_percent"] = (
                    (r - s) / s * 100.0 if s != 0 else None
                )
                comparison[f"rf_vs_semantic_{field}_ratio"] = r / s if s != 0 else None
        comparison["total_latency_saved_ms"] = (
            float(semantic.get("mean_total_ms", 0.0)) - float(rf.get("mean_total_ms", 0.0))
        )
        comparison["plan_latency_saved_ms"] = (
            float(semantic.get("mean_plan_ms", 0.0)) - float(rf.get("mean_plan_ms", 0.0))
        )
        comparison["expanded_nodes_saved"] = (
            float(semantic.get("mean_expanded_nodes", 0.0)) -
            float(rf.get("mean_expanded_nodes", 0.0))
        )
        comparison["build_overhead_ms"] = (
            float(rf.get("mean_build_ms", 0.0)) - float(semantic.get("mean_build_ms", 0.0))
        )
        summary["comparison"] = comparison

    return summary


def fmt_number(value: object, digits: int = 2) -> str:
    if value is None:
        return "N/A"
    return f"{float(value):.{digits}f}"


def fmt_percent(value: object) -> str:
    if value is None:
        return "N/A"
    return f"{float(value):+.2f}%"


def fmt_compact_ms(value: object) -> str:
    if value is None:
        return "N/A"
    value = float(value)
    if abs(value) >= 1000.0:
        return f"{value / 1000.0:.2f} s"
    return f"{value:.1f} ms"


def improvement_text(value: object) -> str:
    if value is None:
        return "N/A"
    return f"{float(value):+.1f}%"


def fmt_speedup(value: object) -> str:
    if value is None:
        return "N/A"
    return f"{float(value):.2f}x"


def build_markdown_table(summary: dict[str, object]) -> str:
    modes = summary["modes"]
    lines = [
        "# Octree Performance Summary",
        "",
        "## Mode Metrics",
        "",
        "| Mode | Total ms | Build ms | Plan ms | Expanded Nodes | Planning Hz | Path Cost |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for mode, data in modes.items():
        lines.append(
            "| "
            f"{mode} | "
            f"{fmt_number(data.get('mean_total_ms'))} | "
            f"{fmt_number(data.get('mean_build_ms'))} | "
            f"{fmt_number(data.get('mean_plan_ms'))} | "
            f"{fmt_number(data.get('mean_expanded_nodes'), 0)} | "
            f"{fmt_number(data.get('planning_hz'), 3)} | "
            f"{fmt_number(data.get('mean_path_cost'))} |"
        )

    comparison = summary.get("comparison", {})
    lines.extend([
        "",
        "## RF Improvement Over Semantic/Baseline Octree",
        "",
        "| Metric | Baseline Mean | RF Mean | Change |",
        "|---|---:|---:|---:|",
    ])
    metric_rows = [
        ("Total time", "total_ms", "ms", 2),
        ("Build time", "build_ms", "ms", 2),
        ("A* plan time", "plan_ms", "ms", 2),
        ("Expanded nodes", "expanded_nodes", "nodes", 0),
        ("Path cost", "path_cost", "cost", 2),
    ]
    semantic = modes.get("semantic_octree_astar", {})
    rf = modes.get("rf_octree_astar", {})
    for label, field, unit, digits in metric_rows:
        baseline = semantic.get(f"mean_{field}")
        current = rf.get(f"mean_{field}")
        improvement = comparison.get(f"rf_vs_semantic_{field}_improvement_percent")
        lines.append(
            "| "
            f"{label} | "
            f"{fmt_number(baseline, digits)} {unit} | "
            f"{fmt_number(current, digits)} {unit} | "
            f"{fmt_percent(improvement)} |"
        )
    lines.extend([
        "",
        "## Derived Poster Metrics",
        "",
        "| Metric | Value | Meaning |",
        "|---|---:|---|",
        f"| Total speedup | {fmt_speedup(comparison.get('semantic_vs_rf_total_ms_speedup'))} | Baseline total time / RF total time |",
        f"| A* planning speedup | {fmt_speedup(comparison.get('semantic_vs_rf_plan_ms_speedup'))} | Baseline A* time / RF A* time |",
        f"| Total latency saved | {fmt_number(comparison.get('total_latency_saved_ms'))} ms | End-to-end time reduced by RF Octree |",
        f"| A* latency saved | {fmt_number(comparison.get('plan_latency_saved_ms'))} ms | Planner time reduced by RF semantics |",
        f"| Expanded nodes saved | {fmt_number(comparison.get('expanded_nodes_saved'), 0)} nodes | Search-space reduction |",
        f"| Build overhead | {fmt_number(comparison.get('build_overhead_ms'))} ms | Extra RF prediction cost during Octree build |",
    ])
    return "\n".join(lines) + "\n"


def write_markdown_table(summary: dict[str, object], output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_markdown_table(summary), encoding="utf-8")
    print(f"Saved table: {output}")


def print_summary(summary: dict[str, object]) -> None:
    print("Performance summary")
    print("===================")
    for mode, data in summary["modes"].items():
        print(f"\n{mode}")
        print(f"  frames: {data['frames']}")
        for field in ["total_ms", "build_ms", "plan_ms", "expanded_nodes", "path_cost"]:
            key = f"mean_{field}"
            if key in data:
                print(f"  {key}: {data[key]:.3f}")
        if data.get("planning_hz") is not None:
            print(f"  planning_hz: {data['planning_hz']:.3f}")
    if "comparison" in summary:
        print("\nRF - semantic improvement")
        for field in ["total_ms", "build_ms", "plan_ms", "expanded_nodes", "path_cost"]:
            key = f"rf_vs_semantic_{field}_improvement_percent"
            if key in summary["comparison"]:
                print(f"  {field}: {summary['comparison'][key]:+.2f}%")
        print(f"  total_speedup: {fmt_speedup(summary['comparison'].get('semantic_vs_rf_total_ms_speedup'))}")
        print(f"  plan_speedup: {fmt_speedup(summary['comparison'].get('semantic_vs_rf_plan_ms_speedup'))}")
        print(f"  total_latency_saved_ms: {summary['comparison'].get('total_latency_saved_ms', 0.0):.3f}")
        print(f"  expanded_nodes_saved: {summary['comparison'].get('expanded_nodes_saved', 0.0):.0f}")


def format_bar_value(metric: str, value: float) -> str:
    if "expanded_nodes" in metric:
        return f"{value:.0f}"
    if metric.endswith("_ms"):
        return f"{value:.1f} ms"
    if metric.endswith("_kb"):
        return f"{value:.0f} KB"
    return f"{value:.2f}"


def annotate_bars(ax, bars, metric: str) -> None:
    values = [bar.get_height() for bar in bars]
    max_value = max(values) if values else 0.0
    y_offset = max(max_value * 0.025, 0.5)
    for bar in bars:
        value = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2.0,
            value + y_offset,
            format_bar_value(metric, value),
            ha="center",
            va="bottom",
            fontsize=8,
        )
    if max_value > 0:
        ax.set_ylim(top=max_value * 1.18)


def maybe_plot(summary: dict[str, object], output: Path) -> None:
    try:
        import matplotlib.pyplot as plt
    except Exception:
        print("matplotlib not available; skipped plot generation")
        return

    modes = list(summary["modes"].keys())
    metrics = ["mean_build_ms", "mean_plan_ms", "mean_total_ms", "mean_expanded_nodes"]
    titles = ["Build ms", "Plan ms", "Total ms", "Expanded nodes"]

    fig, axes = plt.subplots(1, len(metrics), figsize=(16, 4))
    for ax, metric, title in zip(axes, metrics, titles):
        values = [summary["modes"][mode].get(metric, 0.0) for mode in modes]
        bars = ax.bar(modes, values, color=["#3b82f6", "#ef4444"][: len(modes)])
        annotate_bars(ax, bars, metric)
        ax.set_title(title)
        ax.tick_params(axis="x", rotation=25)
    fig.tight_layout()
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=160)
    print(f"Saved plot: {output}")


def maybe_plot_table(summary: dict[str, object], output: Path) -> None:
    try:
        import matplotlib.pyplot as plt
    except Exception:
        print("matplotlib not available; skipped table plot generation")
        return

    modes = summary["modes"]
    semantic = modes.get("semantic_octree_astar", {})
    rf = modes.get("rf_octree_astar", {})
    comparison = summary.get("comparison", {})

    rows = [
        [
            "Total time",
            f"{fmt_number(semantic.get('mean_total_ms'))} ms",
            f"{fmt_number(rf.get('mean_total_ms'))} ms",
            fmt_percent(comparison.get("rf_vs_semantic_total_ms_improvement_percent")),
        ],
        [
            "Build time",
            f"{fmt_number(semantic.get('mean_build_ms'))} ms",
            f"{fmt_number(rf.get('mean_build_ms'))} ms",
            fmt_percent(comparison.get("rf_vs_semantic_build_ms_improvement_percent")),
        ],
        [
            "A* plan time",
            f"{fmt_number(semantic.get('mean_plan_ms'))} ms",
            f"{fmt_number(rf.get('mean_plan_ms'))} ms",
            fmt_percent(comparison.get("rf_vs_semantic_plan_ms_improvement_percent")),
        ],
        [
            "Expanded nodes",
            f"{fmt_number(semantic.get('mean_expanded_nodes'), 0)}",
            f"{fmt_number(rf.get('mean_expanded_nodes'), 0)}",
            fmt_percent(comparison.get("rf_vs_semantic_expanded_nodes_improvement_percent")),
        ],
        [
            "Path cost",
            f"{fmt_number(semantic.get('mean_path_cost'))}",
            f"{fmt_number(rf.get('mean_path_cost'))}",
            fmt_percent(comparison.get("rf_vs_semantic_path_cost_improvement_percent")),
        ],
    ]

    fig, ax = plt.subplots(figsize=(11, 3.2))
    ax.axis("off")
    table = ax.table(
        cellText=rows,
        colLabels=["Metric", "Baseline", "RF / Octree", "Improvement"],
        cellLoc="center",
        colLoc="center",
        loc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1.0, 1.45)
    for (row, col), cell in table.get_celld().items():
        if row == 0:
            cell.set_text_props(weight="bold", color="white")
            cell.set_facecolor("#334155")
        elif col == 3:
            text = cell.get_text().get_text()
            cell.set_facecolor("#fee2e2" if text.startswith("-") else "#dcfce7")
        elif row % 2 == 0:
            cell.set_facecolor("#f8fafc")

    ax.set_title("RF Octree + A* Performance Improvement", weight="bold", pad=14)
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(output, dpi=180)
    print(f"Saved table plot: {output}")


def maybe_plot_poster_chart(summary: dict[str, object], output: Path) -> None:
    try:
        import matplotlib.pyplot as plt
        import numpy as np
    except Exception:
        print("matplotlib not available; skipped poster chart generation")
        return

    modes = summary["modes"]
    semantic = modes.get("semantic_octree_astar", {})
    rf = modes.get("rf_octree_astar", {})

    fig, metrics_ax = plt.subplots(figsize=(15, 8.2), dpi=180)
    fig.patch.set_facecolor("#f8fafc")
    metrics_ax.set_facecolor("#ffffff")

    labels = ["Total\nTime", "A* Plan\nTime", "Expanded\nNodes", "Path\nCost"]
    baseline_values = [
        float(semantic.get("mean_total_ms", 0.0)) / 1000.0,
        float(semantic.get("mean_plan_ms", 0.0)) / 1000.0,
        float(semantic.get("mean_expanded_nodes", 0.0)) / 1000.0,
        float(semantic.get("mean_path_cost", 0.0)),
    ]
    rf_values = [
        float(rf.get("mean_total_ms", 0.0)) / 1000.0,
        float(rf.get("mean_plan_ms", 0.0)) / 1000.0,
        float(rf.get("mean_expanded_nodes", 0.0)) / 1000.0,
        float(rf.get("mean_path_cost", 0.0)),
    ]
    units = ["s", "s", "k nodes", "cost"]
    x = np.arange(len(labels))
    width = 0.36
    bars_a = metrics_ax.bar(
        x - width / 2,
        baseline_values,
        width,
        label="Semantic Octree",
        color="#94a3b8",
    )
    bars_b = metrics_ax.bar(x + width / 2, rf_values, width, label="RF Octree", color="#06b6d4")
    metrics_ax.set_title("Runtime / Search / Memory Comparison", fontsize=24, weight="bold", pad=24)
    metrics_ax.text(
        0.5,
        1.01,
        "Lower bars are better. Path cost includes distance, risk, stair, and vertical-movement penalties.",
        ha="center",
        va="bottom",
        fontsize=13.5,
        color="#475569",
        transform=metrics_ax.transAxes,
    )
    metrics_ax.set_xticks(x, labels, fontsize=17)
    metrics_ax.tick_params(axis="y", labelsize=13)
    metrics_ax.grid(axis="y", color="#cbd5e1", alpha=0.65)
    metrics_ax.set_axisbelow(True)
    metrics_ax.legend(frameon=False, fontsize=14, loc="upper right")
    for bars in [bars_a, bars_b]:
        for idx, bar in enumerate(bars):
            height = bar.get_height()
            metrics_ax.text(
                bar.get_x() + bar.get_width() / 2.0,
                height + max(max(baseline_values + rf_values) * 0.018, 0.02),
                f"{height:.2f} {units[idx]}",
                ha="center",
                va="bottom",
                fontsize=12,
                color="#0f172a",
            )
    metrics_ax.set_ylim(top=max(baseline_values + rf_values) * 1.24 if baseline_values else 1.0)
    metrics_ax.set_ylabel("Seconds / Thousand Nodes / Cost", fontsize=14, color="#334155")
    fig.tight_layout(pad=2.0)

    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, bbox_inches="tight")
    print(f"Saved poster chart: {output}")


def maybe_plot_poster_table(summary: dict[str, object], output: Path) -> None:
    try:
        import matplotlib.pyplot as plt
    except Exception:
        print("matplotlib not available; skipped poster table generation")
        return

    modes = summary["modes"]
    semantic = modes.get("semantic_octree_astar", {})
    rf = modes.get("rf_octree_astar", {})
    comparison = summary.get("comparison", {})
    rows = [
        ["Total time", fmt_compact_ms(semantic.get("mean_total_ms")),
         fmt_compact_ms(rf.get("mean_total_ms")),
         improvement_text(comparison.get("rf_vs_semantic_total_ms_improvement_percent"))],
        ["Octree build time", fmt_compact_ms(semantic.get("mean_build_ms")),
         fmt_compact_ms(rf.get("mean_build_ms")),
         improvement_text(comparison.get("rf_vs_semantic_build_ms_improvement_percent"))],
        ["A* planning time", fmt_compact_ms(semantic.get("mean_plan_ms")),
         fmt_compact_ms(rf.get("mean_plan_ms")),
         improvement_text(comparison.get("rf_vs_semantic_plan_ms_improvement_percent"))],
        ["Expanded nodes", f"{fmt_number(semantic.get('mean_expanded_nodes'), 0)}",
         f"{fmt_number(rf.get('mean_expanded_nodes'), 0)}",
         improvement_text(comparison.get("rf_vs_semantic_expanded_nodes_improvement_percent"))],
        ["Path cost", f"{fmt_number(semantic.get('mean_path_cost'))}",
         f"{fmt_number(rf.get('mean_path_cost'))}",
         improvement_text(comparison.get("rf_vs_semantic_path_cost_improvement_percent"))],
        ["Total speedup", "1.00x",
         fmt_speedup(comparison.get("semantic_vs_rf_total_ms_speedup")),
         fmt_speedup(comparison.get("semantic_vs_rf_total_ms_speedup"))],
        ["A* planning speedup", "1.00x",
         fmt_speedup(comparison.get("semantic_vs_rf_plan_ms_speedup")),
         fmt_speedup(comparison.get("semantic_vs_rf_plan_ms_speedup"))],
    ]

    fig, ax = plt.subplots(figsize=(15, 6.6), dpi=180)
    fig.patch.set_facecolor("#f8fafc")
    ax.axis("off")
    ax.text(
        0.02,
        0.95,
        "Performance Comparison for Indoor Multi-floor Navigation",
        fontsize=25,
        weight="bold",
        color="#0f172a",
        transform=ax.transAxes,
    )
    ax.text(
        0.02,
        0.885,
        "Baseline = semantic Octree + A*. RF Octree uses predicted leaf label and obstacle probability.",
        fontsize=13.5,
        color="#475569",
        transform=ax.transAxes,
    )
    table = ax.table(
        cellText=rows,
        colLabels=["Metric", "Baseline", "RF Octree", "Improvement"],
        cellLoc="center",
        colLoc="center",
        bbox=[0.02, 0.15, 0.96, 0.65],
    )
    table.auto_set_font_size(False)
    table.set_fontsize(16)
    table.scale(1.0, 1.7)
    for (row, col), cell in table.get_celld().items():
        cell.set_edgecolor("#cbd5e1")
        cell.set_linewidth(1.25)
        if row == 0:
            cell.set_text_props(weight="bold", color="white")
            cell.set_facecolor("#0f172a")
        elif col == 0:
            cell.set_text_props(weight="bold", color="#0f172a")
            cell.set_facecolor("#e2e8f0")
        elif col == 3:
            text = cell.get_text().get_text()
            is_negative = text.startswith("-")
            cell.set_text_props(weight="bold", color="#7f1d1d" if is_negative else "#14532d")
            cell.set_facecolor("#fee2e2" if is_negative else "#dcfce7")
        elif row % 2 == 0:
            cell.set_facecolor("#f1f5f9")
        else:
            cell.set_facecolor("#ffffff")

    assumptions = summary.get("assumptions", {})
    ax.text(
        0.02,
        0.075,
        "Memory comparison is omitted because RF prediction changes labels/probabilities, not the Octree topology.",
        fontsize=12.5,
        color="#64748b",
        transform=ax.transAxes,
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, bbox_inches="tight")
    print(f"Saved poster table: {output}")


def main() -> int:
    args = parse_args()
    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(f"Benchmark CSV not found: {input_path}")

    rows = load_rows(input_path)
    if not rows:
        raise RuntimeError(f"No rows found in {input_path}")

    summary = summarize(rows, args.raw_point_bytes, args.point_graph_bytes)
    print_summary(summary)

    output_json = Path(args.output_json)
    output_json.parent.mkdir(parents=True, exist_ok=True)
    output_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(f"Saved JSON: {output_json}")

    write_markdown_table(summary, Path(args.output_table))
    maybe_plot(summary, Path(args.plot))
    maybe_plot_table(summary, Path(args.table_plot))
    maybe_plot_poster_chart(summary, Path(args.poster_chart))
    maybe_plot_poster_table(summary, Path(args.poster_table))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
