#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# RF-Predicted Feature CSV Export Launcher
# ============================================================
#
# Purpose:
#   Build Octree leaves from Gazebo point cloud and immediately overwrite
#   each leaf's label / obstacle_probability with the trained Random Forest.
#
# Output meaning:
#   label / obstacle_probability are already RF predictions. This is useful
#   when you want downstream navigation or visualization to consume model
#   results directly.
#
# Usage:
#   ./scripts/run_feature_export_rf.sh
#   RF_FEATURE_ONCE=1 ./scripts/run_feature_export_rf.sh
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ============================================================
# Parameters You Usually Adjust
# ============================================================

# C++ text model generated by:
#   venv/bin/python3 python/train_model.py
: "${RF_FEATURE_MODEL:=${PROJECT_ROOT}/models/random_forest_voxel_model.rf.txt}"

# Output CSV. The predicted_ prefix keeps python/train_model.py from treating
# this file as another predict input during auto-discovery.
: "${RF_FEATURE_OUTPUT:=${PROJECT_ROOT}/data/predicted_rf_leaf_features.csv}"

# Export only one received cloud and exit. Useful for collecting one snapshot.
: "${RF_FEATURE_ONCE:=0}"

# Keep one CSV per exported frame instead of overwriting the output path.
: "${RF_FEATURE_TIMESTAMPED:=0}"

# Export frequency in Hz when not using RF_FEATURE_ONCE=1.
: "${RF_FEATURE_EXPORT_HZ:=1}"

# Octree and input point limits.
: "${RF_FEATURE_MAX_DEPTH:=9}"
: "${RF_FEATURE_MAX_POINTS:=120000}"

print_usage() {
  cat <<'EOF'
Usage:
  ./scripts/run_feature_export_rf.sh [extra exporter args...]

Purpose:
  Export a CSV whose label / obstacle_probability are already predicted by RF.

Environment overrides:
  RF_FEATURE_MODEL        C++ RF text model, default models/random_forest_voxel_model.rf.txt
  RF_FEATURE_OUTPUT       Output CSV, default data/predicted_rf_leaf_features.csv
  RF_FEATURE_ONCE         1 exports first cloud and exits
  RF_FEATURE_TIMESTAMPED  1 writes one CSV per exported frame
  RF_FEATURE_EXPORT_HZ    Max export frequency
  RF_FEATURE_MAX_DEPTH    Octree max depth
  RF_FEATURE_MAX_POINTS   Max input points per export

Shared overrides forwarded to the exporter:
  GZ_PARTITION_VALUE
  GZ_POINTCLOUD_TOPIC
  FEATURE_FLOOR_Z
  FEATURE_STORY_HEIGHT
  FEATURE_FLOOR_SURFACE_OFFSET
  FEATURE_CEILING_OFFSET
  FEATURE_NEAR_FLOOR
  FEATURE_NEAR_CEILING
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ] || [ "${1:-}" = "help" ]; then
  print_usage
  exit 0
fi

if [ ! -f "${RF_FEATURE_MODEL}" ]; then
  cat >&2 <<EOF
ERROR: RF model not found:
  ${RF_FEATURE_MODEL}

Generate it with:
  venv/bin/python3 python/train_model.py
EOF
  exit 2
fi

# ============================================================
# Fixed Mode Settings
# ============================================================

# This mode always loads RF and never weak-labels / train-prefixes the output.
export FEATURE_OUTPUT="${RF_FEATURE_OUTPUT}"
export FEATURE_ONCE="${RF_FEATURE_ONCE}"
export FEATURE_TIMESTAMPED="${RF_FEATURE_TIMESTAMPED}"
export FEATURE_EXPORT_HZ="${RF_FEATURE_EXPORT_HZ}"
export FEATURE_MAX_DEPTH="${RF_FEATURE_MAX_DEPTH}"
export FEATURE_MAX_POINTS="${RF_FEATURE_MAX_POINTS}"
export FEATURE_TRAIN=0
export FEATURE_WEAK_LABELS=0
export FEATURE_RF_MODEL="${RF_FEATURE_MODEL}"

exec "${SCRIPT_DIR}/run_feature_export.sh" "$@"
