#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# RF Octree + A* Gazebo Path Planning Launcher
# ============================================================
#
# Data flow:
#   DynamicWorldCloud /world/dynamic_cloud
#     -> RF-predicted Octree
#     -> A* planner
#     -> Gazebo Marker line on /marker
#
# Start Gazebo first, for example:
#   ./scripts/run_gazebo.sh gazebo/maps/warehouse_predict_world.sdf -r -v 2
#
# Then run this script in another terminal. By default it uses the visual-only
# start_marker / goal_marker positions in warehouse_predict_world.sdf.
#   ./scripts/run_path_planning.sh
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PLANNER_BIN="${PROJECT_ROOT}/build/rf_octree_path_planner_gazebo"

# ============================================================
# Parameters You Usually Adjust
# ============================================================

# 起點與終點使用 world coordinates，格式固定為 X,Y,Z。
# 預設值對應 warehouse_predict_world.sdf 內的 visual-only start_marker /
# goal_marker。這兩個 marker 沒有 collision，不會被 Octree 取樣成障礙物。
: "${PATH_START:=6,-2,1.2}"
: "${PATH_GOAL:=0,0,9.2}"

# C++ RF model generated by python/train_model.py.
: "${PATH_RF_MODEL:=${PROJECT_ROOT}/models/random_forest_voxel_model.rf.txt}"

# Gazebo transport settings. Must match scripts/run_gazebo.sh.
: "${GZ_PARTITION_VALUE:=dynamic_cloud_test}"
: "${GZ_POINTCLOUD_TOPIC:=/world/dynamic_cloud}"
: "${GZ_MARKER_TOPIC:=/marker}"

# Planning/update rate. 1Hz is usually enough for visualization and avoids
# rebuilding the full Octree too often.
: "${PATH_PLAN_HZ:=1}"

# Octree and input point limits. Increase only if the route misses important
# geometry; higher values cost more CPU/RAM.
: "${PATH_MAX_DEPTH:=9}"
: "${PATH_MAX_POINTS:=50000}"

# A* cost parameters.
# - PATH_BLOCK_PROBABILITY: leaf probability above this value is treated blocked.
# - PATH_OBSTACLE_CLEARANCE_RADIUS: inflate obstacles by this horizontal
#   clearance so the path does not graze boxes/chairs/walls.
# - PATH_OBSTACLE_CLEARANCE_Z_TOLERANCE: only obstacles within this vertical
#   band affect clearance, useful for multi-floor maps.
# - PATH_PROBABILITY_WEIGHT: larger values avoid risky voxels more strongly.
# - PATH_VERTICAL_WEIGHT: larger values penalize unnecessary vertical movement.
# - PATH_STAIR_WEIGHT: cost multiplier when traversing stair voxels.
# - PATH_CROSS_FLOOR_WEIGHT: extra cost on vertical cross-floor edges.
# - PATH_ENDPOINT_SNAP_RADIUS: if start/goal falls on an obstacle leaf, snap to
#   the nearest traversable leaf within this radius.
# - PATH_STAIR_CONNECTION_RADIUS: add virtual stair connector edges within this
#   radius to keep stair/floor connectivity stable across adaptive voxel depths.
# - PATH_CONSTRAIN_STAIR_TRANSITIONS: 1 means free<->stair transitions are only
#   allowed near the bottom/top of each stair component. This prevents entering
#   stairs from the side at mid-height or leaving before the stair is complete.
# - PATH_STAIR_ENDPOINT_TOLERANCE: vertical band treated as a stair endpoint.
# - PATH_STAIR_STEP_MAX_VERTICAL: maximum vertical jump between stair voxels.
# - PATH_STAIR_FLOOR_CONNECTION_MAX_VERTICAL: separate free<->stair vertical
#   gap tolerance for thick floors; keep endpoint tolerance tighter.
# - PATH_MAX_NON_STAIR_VERTICAL_STEP: maximum Z step allowed between two
#   non-stair voxels. Keep below floor thickness to prevent floor tunneling.
# - PATH_STAIR_FLOOR_EXIT_TOLERANCE: stair free<->stair transitions must be
#   within this distance from known floor surfaces (1, 5, 9... by default).
# - PATH_CONSTRAIN_STAIR_DIRECTION: 1 means free<->stair movement must align
#   with the inferred stair facing direction, so entry happens from the first
#   step side instead of the stair sides.
# - PATH_STAIR_DIRECTION_DOT_MIN: larger values enforce a stricter front-facing
#   approach; 0.5 keeps stair entry close to the modeled stair direction.
# - PATH_STAIR_ENTRY_LATERAL_MARGIN: extra side margin for the first/last stair
#   step gate. Lower values reject side entry more aggressively.
# - PATH_STAIR_ENTRY_FORWARD_MARGIN: front/back tolerance around stair endpoints.
: "${PATH_BLOCK_PROBABILITY:=0.92}"
: "${PATH_ENABLE_OBSTACLE_CLEARANCE:=1}"
: "${PATH_OBSTACLE_CLEARANCE_RADIUS:=0.15}"
: "${PATH_OBSTACLE_CLEARANCE_Z_TOLERANCE:=1.5}"
: "${PATH_BLOCK_EDGES_THROUGH_OBSTACLES:=1}"
: "${PATH_EDGE_OBSTACLE_CLEARANCE_RADIUS:=0.03}"
: "${PATH_PROBABILITY_WEIGHT:=6}"
: "${PATH_VERTICAL_WEIGHT:=0.75}"
: "${PATH_STAIR_WEIGHT:=1.25}"
: "${PATH_CROSS_FLOOR_WEIGHT:=2}"
: "${PATH_HEURISTIC_WEIGHT:=1.15}"
: "${PATH_MAX_EXPANSIONS:=200000}"
: "${PATH_ALLOW_CROSS_FLOOR:=1}"
: "${PATH_ENDPOINT_SNAP_RADIUS:=1.5}"
: "${PATH_STAIR_CONNECTION_RADIUS:=1.25}"
: "${PATH_CONSTRAIN_STAIR_TRANSITIONS:=1}"
: "${PATH_STAIR_ENDPOINT_TOLERANCE:=0.6}"
: "${PATH_STAIR_STEP_MAX_VERTICAL:=0.8}"
: "${PATH_STAIR_FLOOR_CONNECTION_MAX_VERTICAL:=1.2}"
: "${PATH_MAX_NON_STAIR_VERTICAL_STEP:=0.35}"
: "${PATH_CONSTRAIN_STAIR_FLOOR_LEVEL_EXITS:=1}"
: "${PATH_STAIR_FLOOR_EXIT_TOLERANCE:=0.45}"
: "${PATH_CONSTRAIN_STAIR_DIRECTION:=1}"
: "${PATH_STAIR_DIRECTION_DOT_MIN:=0.5}"
: "${PATH_STAIR_ENTRY_LATERAL_MARGIN:=0.25}"
: "${PATH_STAIR_ENTRY_FORWARD_MARGIN:=0.55}"

# Marker appearance.
: "${PATH_LINE_WIDTH:=0.08}"
: "${PATH_MARKER_NAMESPACE:=rf_astar_path}"

# RF feature height model for multi-floor buildings.
: "${FEATURE_FLOOR_Z:=0}"
: "${FEATURE_STORY_HEIGHT:=4}"
: "${FEATURE_FLOOR_SURFACE_OFFSET:=1}"
: "${FEATURE_CEILING_OFFSET:=4}"
: "${FEATURE_NEAR_FLOOR:=0.4}"
: "${FEATURE_NEAR_CEILING:=0.4}"

print_usage() {
  cat <<'EOF'
Usage:
  ./scripts/run_path_planning.sh [extra planner args...]

Start / goal:
  PATH_START                 Start position, default "6,-2,1.2"
  PATH_GOAL                  Goal position, default "0,0,9.2"

Common overrides:
  PATH_RF_MODEL              RF text model path
  GZ_PARTITION_VALUE         Gazebo partition, must match run_gazebo.sh
  GZ_POINTCLOUD_TOPIC        DynamicWorldCloud topic
  GZ_MARKER_TOPIC            Marker topic, default /marker
  PATH_PLAN_HZ               Replan frequency
  PATH_MAX_DEPTH             Octree max depth
  PATH_MAX_POINTS            Max point count used per frame
  PATH_BLOCK_PROBABILITY     Probability threshold treated as blocked
  PATH_OBSTACLE_CLEARANCE_RADIUS Inflate obstacles by this radius
  PATH_OBSTACLE_CLEARANCE_Z_TOLERANCE Vertical band for obstacle clearance
  PATH_BLOCK_EDGES_THROUGH_OBSTACLES 1 blocks path segments through obstacles
  PATH_EDGE_OBSTACLE_CLEARANCE_RADIUS Hard path-segment obstacle margin
  PATH_PROBABILITY_WEIGHT    Risk avoidance weight
  PATH_VERTICAL_WEIGHT       Vertical movement penalty
  PATH_ALLOW_CROSS_FLOOR     1 allow stairs/cross-floor edges, 0 disable
  PATH_ENDPOINT_SNAP_RADIUS  Snap start/goal to nearest traversable leaf
  PATH_STAIR_CONNECTION_RADIUS Nearby stair connector edge radius
  PATH_CONSTRAIN_STAIR_TRANSITIONS 1 constrain stair entry/exit to endpoints
  PATH_STAIR_ENDPOINT_TOLERANCE Stair endpoint entry/exit height band
  PATH_STAIR_STEP_MAX_VERTICAL Max vertical jump between stair voxels
  PATH_STAIR_FLOOR_CONNECTION_MAX_VERTICAL Max free<->stair vertical gap
  PATH_MAX_NON_STAIR_VERTICAL_STEP Max non-stair Z step before blocking
  PATH_CONSTRAIN_STAIR_FLOOR_LEVEL_EXITS 1 restrict stair exits to floor levels
  PATH_STAIR_FLOOR_EXIT_TOLERANCE Stair exit floor-level tolerance
  PATH_CONSTRAIN_STAIR_DIRECTION 1 require entry/exit to match stair facing
  PATH_STAIR_DIRECTION_DOT_MIN Stair facing dot-product threshold
  PATH_STAIR_ENTRY_LATERAL_MARGIN Stair entrance side-entry tolerance
  PATH_STAIR_ENTRY_FORWARD_MARGIN Stair entrance front/back tolerance
  PATH_LINE_WIDTH            Gazebo marker line width
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ] || [ "${1:-}" = "help" ]; then
  print_usage
  exit 0
fi

if [ ! -x "${PLANNER_BIN}" ]; then
  cat >&2 <<EOF
ERROR: Planner binary not found:
  ${PLANNER_BIN}

Build it with:
  cmake --build build --target rf_octree_path_planner_gazebo
EOF
  exit 2
fi

if [ ! -f "${PATH_RF_MODEL}" ]; then
  cat >&2 <<EOF
ERROR: RF model not found:
  ${PATH_RF_MODEL}

Generate it with:
  venv/bin/python3 python/train_model.py
EOF
  exit 3
fi

ARGS=(
  --partition "${GZ_PARTITION_VALUE}"
  --topic "${GZ_POINTCLOUD_TOPIC}"
  --marker-topic "${GZ_MARKER_TOPIC}"
  --marker-namespace "${PATH_MARKER_NAMESPACE}"
  --rf-model "${PATH_RF_MODEL}"
  --start "${PATH_START}"
  --goal "${PATH_GOAL}"
  --plan-hz "${PATH_PLAN_HZ}"
  --max-depth "${PATH_MAX_DEPTH}"
  --max-points "${PATH_MAX_POINTS}"
  --block-probability "${PATH_BLOCK_PROBABILITY}"
  --obstacle-clearance-radius "${PATH_OBSTACLE_CLEARANCE_RADIUS}"
  --obstacle-clearance-z-tolerance "${PATH_OBSTACLE_CLEARANCE_Z_TOLERANCE}"
  --edge-obstacle-clearance-radius "${PATH_EDGE_OBSTACLE_CLEARANCE_RADIUS}"
  --probability-weight "${PATH_PROBABILITY_WEIGHT}"
  --vertical-weight "${PATH_VERTICAL_WEIGHT}"
  --stair-weight "${PATH_STAIR_WEIGHT}"
  --cross-floor-weight "${PATH_CROSS_FLOOR_WEIGHT}"
  --heuristic-weight "${PATH_HEURISTIC_WEIGHT}"
  --max-expansions "${PATH_MAX_EXPANSIONS}"
  --endpoint-snap-radius "${PATH_ENDPOINT_SNAP_RADIUS}"
  --stair-connection-radius "${PATH_STAIR_CONNECTION_RADIUS}"
  --stair-endpoint-tolerance "${PATH_STAIR_ENDPOINT_TOLERANCE}"
  --stair-step-max-vertical "${PATH_STAIR_STEP_MAX_VERTICAL}"
  --stair-floor-connection-max-vertical "${PATH_STAIR_FLOOR_CONNECTION_MAX_VERTICAL}"
  --max-non-stair-vertical-step "${PATH_MAX_NON_STAIR_VERTICAL_STEP}"
  --stair-floor-exit-tolerance "${PATH_STAIR_FLOOR_EXIT_TOLERANCE}"
  --stair-direction-dot-min "${PATH_STAIR_DIRECTION_DOT_MIN}"
  --stair-entry-lateral-margin "${PATH_STAIR_ENTRY_LATERAL_MARGIN}"
  --stair-entry-forward-margin "${PATH_STAIR_ENTRY_FORWARD_MARGIN}"
  --line-width "${PATH_LINE_WIDTH}"
  --floor-z "${FEATURE_FLOOR_Z}"
  --story-height "${FEATURE_STORY_HEIGHT}"
  --floor-surface-offset "${FEATURE_FLOOR_SURFACE_OFFSET}"
  --ceiling-offset "${FEATURE_CEILING_OFFSET}"
  --near-floor "${FEATURE_NEAR_FLOOR}"
  --near-ceiling "${FEATURE_NEAR_CEILING}"
)

if [ "${PATH_ALLOW_CROSS_FLOOR}" = "0" ]; then
  ARGS+=(--no-cross-floor)
fi

if [ "${PATH_CONSTRAIN_STAIR_TRANSITIONS}" = "0" ]; then
  ARGS+=(--no-stair-transition-constraint)
fi

if [ "${PATH_CONSTRAIN_STAIR_FLOOR_LEVEL_EXITS}" = "0" ]; then
  ARGS+=(--no-stair-floor-level-exit-constraint)
fi

if [ "${PATH_CONSTRAIN_STAIR_DIRECTION}" = "0" ]; then
  ARGS+=(--no-stair-direction-constraint)
fi

if [ "${PATH_ENABLE_OBSTACLE_CLEARANCE}" = "0" ]; then
  ARGS+=(--no-obstacle-clearance)
fi

if [ "${PATH_BLOCK_EDGES_THROUGH_OBSTACLES}" = "0" ]; then
  ARGS+=(--no-edge-obstacle-blocking)
fi

exec "${PLANNER_BIN}" "${ARGS[@]}" "$@"
