#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# RF-Predicted Octree 3D Visualization Launcher
# ============================================================
#
# Purpose:
#   Show the same Gazebo point cloud as an Octree, but use the trained RF
#   model to predict each leaf's label / obstacle_probability before rendering.
#
# Recommended comparison:
#   Terminal A: ./scripts/run_visualization.sh octree
#   Terminal B: ./scripts/run_visualization_rf.sh
#

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# C++ text model generated by:
#   venv/bin/python3 python/train_model.py
: "${OCTREE_RF_MODEL:=${PROJECT_ROOT}/models/random_forest_voxel_model.rf.txt}"

# Distinct title so it is easy to compare with the Gazebo-semantic viewer.
: "${OCTREE_WINDOW_TITLE:=RF Predicted Navigation Octree}"

print_usage() {
  cat <<'EOF'
Usage:
  ./scripts/run_visualization_rf.sh [extra octree viewer args...]

Environment overrides:
  OCTREE_RF_MODEL          RF text model path
  OCTREE_WINDOW_TITLE      Viewer title
  OCTREE_COLOR_MODE        probability, label, or depth
  OCTREE_VOXEL_MODE        centers, boxes, hybrid, or center-boxes
  OCTREE_MAX_VOXELS
  OCTREE_MAX_RENDER_POINTS
  OCTREE_REBUILD_HZ
  GZ_PARTITION_VALUE
  GZ_POINTCLOUD_TOPIC
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ] || [ "${1:-}" = "help" ]; then
  print_usage
  exit 0
fi

if [ ! -f "${OCTREE_RF_MODEL}" ]; then
  cat >&2 <<EOF
ERROR: RF model not found:
  ${OCTREE_RF_MODEL}

Generate it with:
  venv/bin/python3 python/train_model.py
EOF
  exit 2
fi

export OCTREE_RF_MODEL
export OCTREE_WINDOW_TITLE

exec "${SCRIPT_DIR}/run_visualization.sh" octree-rf "$@"
